version: "2"

services:
  virtualdesktop:
    image: "localhost:5000/systemctl/virtualdesktop"
    expose: [ 5599, 4444 ]
    ports:
      - "5599:5599"
      - "4444:4444"
  serversystem:
    image: "localhost:5000/systemctl/serversystem"
    expose: [ 8080 ]
    ports:
       - "8080:8080"
