version: "2"

services:
  virtualdesktop:
    image: "centos:7.4.1708"
    command: "sleep 9999"
    expose: [ 5599, 4444 ]
    ports:
       - "5590:5599"
  serversystem:
    image: "centos:7.4.1708"
    command: "sleep 9999"
    expose: [ 8080 ]
    ports:
       - "8090:8080"
