- hosts: localhost
  tasks:
     - include_vars: "roles/selenium-server/defaults/main.yml"
     - set_fact:
         selenium_python_validate_certs: no # TLSv1 warning
         selenium_geckodriver_validate_certs: no # TLSv1 warning
     - include: "roles/selenium-server/tasks/software_download-server.yml"
     - include: "roles/selenium-server/tasks/software_download-python.yml"
     - include: "roles/selenium-server/tasks/software_download-geckodriver.yml"
