# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: install dir
  file: path="{{selenium_server_dir}}" state="directory" owner="{{ansible_user}}"
  become: yes
- name: install pkg
  shell: |
     cp -v "{{selenium_server_software}}/{{selenium_server_package}}" "{{selenium_server_dir}}/"
     ls -ld "{{selenium_server_dir}}"/*
  become: yes
  register: installed
- debug: var=installed.stdout_lines
