- include: software_upload-server.yml
- include: software_upload-python.yml
- include: software_upload-geckodriver.yml
- include: software_download-server.yml
  when: LOCAL is undefined
- include: software_download-python.yml
  when: LOCAL is undefined
- include: software_download-geckodriver.yml
  when: LOCAL is undefined
- include: install_java.yml
- include: install_selenium-server.yml
- include: install_selenium-python.yml
- include: install_selenium-geckodriver.yml
- include: install_systemd.yml
- include: enable_software.yml
- include: cleanrepo.yml
