# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: upload check
  local_action: 'stat path="{{selenium_geckodriver_software}}/{{selenium_geckodriver_package}}"'
  register: have_download
- name: inst dir
  file: path="{{selenium_geckodriver_software}}" state="directory" owner="{{ansible_user}}"
- name: upload rpm
  copy: src="../{{selenium_geckodriver_software}}/{{selenium_geckodriver_package}}" dest="{{selenium_geckodriver_software}}"
  when: have_download.stat.exists
