# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: install rpm
  yum: name="{{jenkins_software}}/{{jenkins_rpm}}" state="present"
- name: jenkins prefix and args
  lineinfile:
     dest: "{{jenkins_sysconfig_file}}"
     state: present
     regexp: '^JENKINS_ARGS=.*'
     line: 'JENKINS_ARGS="--prefix={{jenkins_prefix}} {{jenkins_args}}"'
- name: jenkins java options
  lineinfile:
     dest: "{{jenkins_sysconfig_file}}"
     state: present
     regexp: '^JENKINS_JAVA_OPTIONS=.*'
     line: 'JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true {{jenkins_options}}"'
