# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: download check
  stat: path="{{jenkins_software}}/{{jenkins_rpm}}"
  register: need_download
- name: "mkdir {{jenkins_software}}"
  file:
    path: "{{jenkins_software}}"
    owner: "{{ansible_user}}"
    state: "directory"
- name: download {{jenkins_package}}
  get_url:
    dest: "{{jenkins_software}}"
    url: "{{jenkins_download}}/{{jenkins_rpm}}"
  when: not need_download.stat.exists
