# Copyright (C) 2017 Guido U. Draheim, All Rights Reserved

- name: upload check
  stat: path="tests/{{jenkins_software}}/{{jenkins_rpm}}"
  register: have_download1
- name: upload check
  local_action: 'stat path="{{jenkins_software}}/{{jenkins_rpm}}"'
  register: have_download
- name: inst dir
  file: path="{{jenkins_software}}" state="directory" owner="{{ansible_user}}"
- name: upload rpm
  copy: src="../{{jenkins_software}}/{{jenkins_rpm}}" dest="{{jenkins_software}}"
  when: have_download.stat.exists
